language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - master

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

branches:
  only:
    - master
    - travis
    - ci

before_script:
  - composer install

script:
  - phpunit --coverage-text

